# Question 1

Use a foreach loop to repeat 100 times:

generate a random sample from an exponential distribution with mean 1

calculate mean and variance

row-bind your results (rbind) (results = mean and variance).

# Question 2

Use the doParallel package and foreach to bootstrap the median for the galaxies data (in library MASS).

If the foreach function needs access to data or a function from a certain package, this can be done by adding the .packages='MASS' (for example) argument.

How does processing time compare to that of serial processing? If each iteration’s run time is small, relative to the amount of data that needs to be loaded and returned, parallel processing might not actually speed up the total run time. Bootstrapping is relatively small: draw a sample, calculate a statistic. It might only start making a difference if each chunk becomes large relatively to the overheads of data transfer. Experiment with this. Try doing 1000 bootstrap samples at a time instead of managing single bootstrap samples.

# Question 3

Estimate coverage of a percentile bootstrap confidence interval for the following scenario: sample of size 50 from an exponential distribution with mean 1.

# Question 4

The package iterators provides several functions that can be used to create sequences for the foreach function. For example, the irnorm function creates an object that iterates over vectors of normally distributed random numbers. It is useful when you need to use random variables drawn from one distribution in an expression that is run in parallel.

In this exercise, use the foreach and irnorm functions to iterate over 3 vectors, each containing 5 random variables. Find the largest value in each vector, and print those largest values.

Before running the foreach function set the seed to 1234.

# Question 5

Compare run time between parLapply, foreach and replicate for the above problem.
